### ISSUE TITLE
Build Automation

### ISSUE THREAD

**Issue by StarWitch** [taisei-project/taisei#269]
To track everything related to build automation.

REVIEW ORDER:
- [x] ~~Windows Test CI #286~~
- [x] ~~Emscripten Test CI #296~~
- [x] ~~Switch Test CI #299~~
- [x] Release Automation #289 
- [x] Dockerfiles #278
- [x]  Makefile #292

TODO:
- [x] Turn `werror` back on (once `master` has been fixed)
- [x] `.zip` needs packaging (Windows)
- [x] x86 binary & packaging for `.zip` and `.exe` (Windows)
- [x] Emscripten build (Web) (⚠️ requires upstream fixes to work properly, but it's "complete" for now)
- [x] Build/package `libGLESv2.dll`/`libEGL.dll` into own repo (Windows)
- [x] Set GL ES 3.0 (Windows)
- [x] Homebrew Switch build (Switch)
- [x] Apple Silicon build
- [x] `.tar.xz` of raw source code
- [x] Generate `.sig` files (store key in GitHub Secrets)
- [x] Testing if tag prefixes and suffixes work (i.e: `v1.4.0-alpha`, `v1.3.3-rc`).
- [x] #357

NICE TO HAVES:
- [x] Automatic "weekly" build/upload of `master` Emscripten builds to a GitHub Page (partially complete in forked repo)
- [ ] Publish the changelog to `taisei-project.org` as a blog post
- [x] Since GHA gives unlimited minutes to public repos... have GHA compile ANGLE???? (haha, no)

POST-MERGE CHECKLIST:
- [ ] Add **Deploy Key** for nightly/weekly Emscripten builds (`EMSCRIPTEN_WEEKLY_DEPLOY_KEY`)
- [x] Add **GPG Key** for signing builds (`GPG_PRIVATE_KEY`/`GPG_PASSPHRASE`)
- [ ] Move `taisei-project.org` to the GitHub Pages repo `taisei-website-new`

**Comment by StarWitch** [comment]
95% of the stuff here has been finished. Closing.
