### ISSUE TITLE
Extra Stage

### ISSUE THREAD

**Issue by StarWitch** [taisei-project/taisei#365]
Much of this work is already done in the `[spoilers]` branch. This is to track it as part of the v1.4 "project."

## Todo

- [ ] Rebase branch up to modern standards
- [ ] Stage mob patterns
- [ ] Mid-boss patterns
- [ ] Boss patterns
- [ ] Edit dialogue (@StarWitch)
- [ ] Stage BGM (finish)
- [ ] Boss BGM (refresh/edit)
