### ISSUE TITLE
Improvements to Kiosk/Event Mode

### ISSUE THREAD

**Issue by StarWitch** [taisei-project/taisei#366]
Some things noticed as part of Dokomi 2023.

## Todo

- [ ] Timeout back to main menu on Continue screen 
- [ ] Ability to exfiltrate replays
- [ ] Better controller support in menus

**Comment by Akaricchi** [comment]
This is basically done now as of the DoKomi 2024 build/upcoming v1.4.2
